name: TV Card Phoenix
description: 📺 TV Remote Card Phoenix
type: lovelace
keywords:
  - tvcard
  - remote
  - tv
  - television
author:
  name: mar_robHD & Misaka
license: Apache License, Version 2.0
files:
  - tv-card-phoenix-tv.js
  - tv-card-phoenix-tv-editor.js
